services:


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on: 
      - backend 
    
  backend:
    build:
      context: ./backend          # Path to backend folder
      dockerfile: backend.Dockerfile      # Name of the Dockerfile (default is "Dockerfile")
    container_name: express-backend
    ports:
      - "3000:3000"
  
  gitea:
    image: gitea/gitea:1.22.0
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data   # Stores repos and configs persistently
    ports:
      - "4000:3000"     # Gitea web UI now on http://localhost:4000
      - "222:22"        # SSH for Git
    restart: always


  # git-server:
